name: waterpact-paper-archive
channels:
  - defaults
dependencies:
  - python=3.11
  - pip
  - numpy
  - scipy
  - pandas
  - matplotlib
  - ipython
  - ipykernel
  - jupyterlab
  - nbclient
  - nbformat
  - pip:
      - scikit-optimize
      - cmocean
